#!/usr/bin/env python3
"""Run the local Script-Hub service to build Shadowrocket modules.

The GitHub Actions workflow checks out Script-Hub's source and starts its
``service.js`` locally.  This script calls the source-backed rewrite parser;
it deliberately does not use the hosted script.hub service.
"""

from __future__ import annotations

import argparse
import os
import re
import tempfile
from pathlib import Path
from urllib.request import Request, urlopen


OUTPUT_DIR = Path("shadowrocket")
TIMEOUT = 180
USER_AGENT = "ad-domain-rules-shadowrocket-updater"

MODULES = (
    (
        "rewrite",
        "https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/rewrite.snippet",
    ),
    (
        "XWebAds",
        "https://raw.githubusercontent.com/fmz200/wool_scripts/refs/heads/main/QuantumultX/rewrite/XWebAds.snippet",
    ),
    (
        "weibo",
        "https://raw.githubusercontent.com/fmz200/wool_scripts/refs/heads/main/QuantumultX/rewrite/weibo.snippet",
    ),
)

MODULE_HEADER_RE = re.compile(r"^#!name=\S", re.IGNORECASE | re.MULTILINE)
MODULE_SECTION_RE = re.compile(
    r"^\[(?:General|Script|URL Rewrite|Header Rewrite|MITM)\]\s*$",
    re.IGNORECASE | re.MULTILINE,
)


def conversion_url(base_url: str, name: str, source_url: str) -> str:
    """Build Script-Hub's local ``file/_start_`` rewrite-parser URL.

    Script-Hub intentionally keeps the source URL as a path segment.  The
    three configured sources contain no query string, so preserving the URL
    verbatim matches the URL generated by Script-Hub's own frontend.
    """

    source_url = source_url.split("#", 1)[0]
    return (
        f"{base_url.rstrip('/')}/file/_start_/{source_url}/_end_/"
        f"{name}.sgmodule?type=qx-rewrite&target=shadowrocket-module&del=true"
    )


def fetch_module(url: str) -> str:
    request = Request(url, headers={"User-Agent": USER_AGENT})
    with urlopen(request, timeout=TIMEOUT) as response:  # noqa: S310 - local CI service URL
        return response.read().decode("utf-8", "replace")


def validate_module(name: str, content: str) -> None:
    if not content.strip():
        raise RuntimeError(f"Script-Hub returned an empty module for {name}")
    if "<html" in content[:1000].lower():
        raise RuntimeError(f"Script-Hub returned an HTML page for {name}")
    if not MODULE_HEADER_RE.search(content):
        raise RuntimeError(f"Script-Hub output for {name} has no Shadowrocket module header")
    if not MODULE_SECTION_RE.search(content):
        raise RuntimeError(f"Script-Hub output for {name} has no Shadowrocket module section")


def _strip_domains(content: str, domains: tuple[str, ...]) -> str:
    """Drop rules that target any of the given domains from a module's content.

    Lines (scripts, comments, URL rewrites) mentioning a domain are removed
    entirely.  A MITM ``hostname = ...`` line is a shared domain list, so only
    the matching entries are dropped and the rest of the line is kept.
    """
    # Each domain's dots may appear plain (hostname lists) or backslash-escaped
    # (regex-style rules), e.g. dfcfw.com vs j5\.dfcfw\.com.
    pattern = re.compile(
        "|".join(domain.replace(".", r"(?:\.|\\\.)") for domain in domains),
        re.IGNORECASE,
    )
    out: list[str] = []
    for line in content.splitlines():
        if not pattern.search(line):
            out.append(line)
            continue
        stripped = line.strip()
        if stripped.startswith("hostname") and "=" in line:
            key, _, rest = line.partition("=")
            keep = [
                part.strip()
                for part in rest.split(",")
                if part.strip() and not pattern.search(part)
            ]
            if keep:
                out.append(key + "= " + ", ".join(keep))
            continue
        # Any other line referencing one of the domains is dropped.
    return "\n".join(out)


def update_modules(base_url: str) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    pending: list[tuple[Path, Path]] = []

    with tempfile.TemporaryDirectory(prefix=".shadowrocket-", dir=OUTPUT_DIR.parent) as temp_dir:
        temp_root = Path(temp_dir)
        for name, source_url in MODULES:
            endpoint = conversion_url(base_url, name, source_url)
            print(f"Converting {source_url} -> {OUTPUT_DIR / (name + '.sgmodule')}")
            content = fetch_module(endpoint)
            if name == "rewrite":
                # The upstream snippet bundles rules we do not want; drop
                # lines and hostname entries targeting these domains.
                content = _strip_domains(content, ("ithome.com", "dfcfw.com"))
            validate_module(name, content)
            temporary_output = temp_root / f"{name}.sgmodule"
            temporary_output.write_text(content, encoding="utf-8", newline="\n")
            pending.append((temporary_output, OUTPUT_DIR / f"{name}.sgmodule"))

        for temporary_output, output in pending:
            os.replace(temporary_output, output)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base-url",
        default=os.environ.get("SCRIPTHUB_BASE_URL", "http://127.0.0.1:9100"),
        help="Base URL of the locally running Script-Hub service",
    )
    args = parser.parse_args()
    update_modules(args.base_url)


if __name__ == "__main__":
    main()
